[global]
address = 0.0.0.0
port = 5000
debug = False

[database]
file = lwp.db

[session]
time = 10
secret_key = a104b8dd3d99f5005fdaef3aced281ff9d9c639d225182bd3203724053d7add5

[overview]
partition = /
